version: "3"

services:
  redis:
    image: redis:4.0.1-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379"

  api:
    build:
      context: .
      dockerfile: .
    volumes:
      - .:/code/
    environment: &environment
      - ALFRED_REDIS_HOST=redis
    ports:
      - "8108:8108"
    depends_on:
      - "redis"
    # https://github.com/Eficode/wait-for
    command: pytest -s --cov-report term-missing --cov-fail-under 100

volumes:
  redis-data:
