version: "3"

services:
  redis:
    image: redis:4.0.1-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/task
    environment: &environment
      - ALFRED_REDIS_HOST=redis
      - ALFRED_PASSWORD_SALT=esquilo
    ports:
      - "8108:8108"
    depends_on:
      - "redis"

volumes:
  redis-data:
